FOGL-5144: handling of bearer token - security category - sendToDispatcher
fledge-iot/fledge-service-notification pull request #30
Opened 2021-10-25 12:45 UTC by pintomax

2021-11-04 09:25 UTC, MarkRiddoch reviewed
I don't see a ServiceAuthHandler class in this PR, is this something you need to add?

2022-02-10 10:27 UTC, pintomax commented
This PR needs Fledge branch "FOGL-5144_bearer_token_verification"

2022-02-10 12:14 UTC, MarkRiddoch requested changes
Please preserve the indentation in the header file

2022-02-10 12:14 UTC, MarkRiddoch commented on C/services/common/include/notification_service.h
> +		NotificationApi*  m_api;
Indentation

2022-02-11 14:40 UTC, MarkRiddoch submitted a review, later dismissed

2022-03-01 09:25 UTC, MarkRiddoch approved these changes

2022-06-01 10:26 UTC, MarkRiddoch submitted a review, later dismissed

2022-06-06 09:28 UTC, MarkRiddoch submitted a review, later dismissed

2022-06-13 08:42 UTC, MarkRiddoch approved these changes

2022-06-13 08:44 UTC, merged