FOGL-7103: Modified to restart notification service in case of SIGTERM…
fledge-iot/fledge-service-notification pull request #61
Opened 2022-12-07 08:26 UTC by gnandan

… signal

Signed-off-by: nandan <nandan.ghildiyal@gmail.com>

2022-12-09 16:27 UTC, MarkRiddoch requested changes
I think we have a fundamental misunderstanding here. The expectation was that the process should be restarted by the core, not that the process calls an internal restart routine. Hence the suggested change was to handle SIGTERM as it was being handled, just avoid the step of unregistering with the core as that stopped the monitoring services within the Fledge core restarting the process.

2022-12-12 15:30 UTC, MarkRiddoch requested changes
Just minor typo

2022-12-12 15:30 UTC, MarkRiddoch commented on C/services/common/include/notification_service.h
> +		void 			stop(bool remvoeFromCore=true);
typo removeFromCore

2022-12-12 15:30 UTC, MarkRiddoch commented on C/services/common/notification_service.cpp
> +void NotificationService::stop(bool remvoeFromCore)
removeFromCore

2022-12-12 15:30 UTC, MarkRiddoch commented on C/services/common/notification_service.cpp
> +	if (remvoeFromCore == false)
removeFromCore

2022-12-12 16:05 UTC, gnandan commented on C/services/common/notification_service.cpp
> +	if (remvoeFromCore == false)
typo is fixed

2022-12-13 12:05 UTC, MarkRiddoch approved these changes

2022-12-13 12:49 UTC, merged