FOGL-7448 Update notification documentation
fledge-iot/fledge-service-notification pull request #70
Opened 2023-02-10 16:43 UTC by MarkRiddoch

Signed-off-by: Mark Riddoch <mark@dianomic.com>

2023-02-10 16:54 UTC, pintomax approved these changes

2023-02-15 13:39 UTC, ashish-jabble requested changes

2023-02-16 07:10 UTC, ashish-jabble approved these changes

2023-02-16 08:52 UTC, merged

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +may be either when a condition that was previously not met being is,
not met being is?

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +as long as that condition is met.
can be written better

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +in the rest of the system; it will still for example follow the normal
it will still `for example` follow ?

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +statistics data, the raw statistic increments as they occur or the
raw statistic increments or raw statistic incremented value?

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +it tends to be non-numeric and most plugins expect to sue numeric data.
sue - > use*

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +posted with the audit log entry as the data points of the data. There is a
data points?

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +to monitor is the same as the name of the service.
Can we use `Readings sent` for total sent as well? or only service name are allowed.

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +This will cause the notification to trigger if the value of the statistic
value of the statistic rate

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +alert is required when the flow drops of to use the 8Average* filter and
8Average* -> *Average*

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +cause fail over to a standby system.
failover  (no space)

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +The audit code we will use in this case is SRVRG which is written whenever
in this case -> in this example

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +As with any notification we start by creating a naming the notification. Then we select the notification rule plugin. In this case we will use the *Data Availability* plugin. This rule triggers every
creating a naming?

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +As with any notification we start by creating a naming the notification. Then we select the notification rule plugin. In this case we will use the *Data Availability* plugin. This rule triggers every
audit name  -> audit code

2023-02-16 13:18 UTC, praveen-garg commented on docs/index.rst
> +We enter the required audit code in the *Audit Code* field. If we wanted to monitor several audit codes we could a comma separated list, however in this case one entry is sufficient.
If we wanted to monitor several audit codes we could a comma separated list

If we want to monitor several audit codes we could enter a comma separated list e.g. SRVRG, SRVUN,