FOGL-7495: FogLAMP: Audit Log NTFSN generated even when delivery fails.
fledge-iot/fledge-service-notification pull request #77
Opened 2023-03-16 14:50 UTC by Innovative-ashwin

2023-03-17 05:20 UTC, gnandan reviewed
Looks good. Please test it with different notification for complete coverage.

2023-03-20 10:49 UTC, MarkRiddoch requested changes

2023-03-20 10:49 UTC, MarkRiddoch commented on C/services/notification/delivery_queue.cpp
> +                         m_logger->debug("Delivery plugin returned failure on notify, Could not add audit Log for instanceName %s, and reason %s", instanceName.c_str(), reason.c_str());
Please make this a warning

2023-03-23 11:22 UTC, Innovative-ashwin commented on C/services/notification/delivery_queue.cpp
> +                std::string reason = elem->getData()->getReason();
fixed

2023-03-23 14:48 UTC, MarkRiddoch approved these changes

2023-03-23 14:54 UTC, merged